# Generated by Django 4.1.3 on 2022-12-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookantinauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='type',
            field=models.CharField(choices=[('SELLER', 'SELLER'), ('CUSTOMER', 'CUSTOMER'), ('ADMIN', 'ADMIN')], default='CUSTOMER', max_length=10),
        ),
    ]
