# Generated by Django 4.1.3 on 2022-12-01 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookantinauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('price', models.IntegerField()),
                ('type', models.CharField(choices=[('FOOD', 'FOOD'), ('DRINK', 'DRINK')], default='FOOD', max_length=10)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookantinauth.seller')),
            ],
        ),
    ]
