# Generated by Django 4.1.3 on 2022-12-01 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookantinauth', '0001_initial'),
        ('menuapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='bookantinauth.seller'),
        ),
    ]
