# Generated by Django 4.1.3 on 2022-12-03 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menuapp', '0002_alter_menu_seller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkedOut', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('SEDANG_MEMESAN', 'SEDANG_MEMESAN'), ('MENUNGGU_PEMBAYARAN', 'MENUNGGU_PEMBAYARAN'), ('MENGKONFIRMASI_PEMBAYARAN', 'MENGKONFIRMASI_PEMBAYARAN'), ('DIPROSES', 'DIPROSES'), ('SIAP_DIAMBIL', 'SIAP_DIAMBIL')], default='SEDANG_MEMESAN', max_length=30)),
                ('checkOutTime', models.DateTimeField(blank=True, default=None, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_content', to='tesapp.cart')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuapp.menu')),
            ],
        ),
    ]
