# Generated by Django 4.1.3 on 2022-12-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesapp', '0003_cart_checkouttime_cart_createddate_cart_lastupdated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='createdDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='lastUpdated',
            field=models.DateField(null=True),
        ),
    ]
