# Generated by Django 4.1.3 on 2022-12-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesapp', '0004_alter_cart_createddate_alter_cart_lastupdated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='checkOutTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='createdDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='lastUpdated',
            field=models.DateTimeField(null=True),
        ),
    ]
