# Generated by Django 4.1.3 on 2022-12-03 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0002_alter_menu_seller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tesapp', '0005_alter_cart_checkouttime_alter_cart_createddate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='cartcontent',
            name='cartId',
        ),
        migrations.RemoveField(
            model_name='cartcontent',
            name='menuId',
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartcontent',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='tesapp.cart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartcontent',
            name='currentPrice',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartcontent',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='menuapp.menu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='lastUpdated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('menunggu_pembayaran', 'menunggu_pembayaran'), ('diproses', 'diproses'), ('siap_diambil', 'siap_diambil')], default='menunggu_pembayaran', max_length=30),
        ),
    ]
