# Generated by Django 4.1.3 on 2022-12-02 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_alter_cart_checkedout_alter_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='checkOutTime',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='createdDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='lastUpdated',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('diproses', 'diproses'), ('siap_diambil', 'siap_diambil')], default='diproses', max_length=30),
        ),
    ]
